import re


# Strong-signal patterns: content phrased as a command to override the agent's own behavior/safety
# rules (Dash et al.'s "Explicit Command Insertion" class — see ../aip444-research/literature/
# 06-dash-memory-poisoning.md). This is a deny-list, so it's well-suited to exactly this class of
# attack and not to subtler, non-imperative phrasing (see Implementation notes below once written).
BEHAVIOR_OVERRIDE_PATTERNS = [
    r"\bignore (all|any|previous|prior|future) .*(safety|instruction|warning|rule)",
    r"\bdisregard (all|any|previous|prior|future) .*(safety|instruction|warning|rule)",
    r"\byou are now\b",
    r"\bfrom now on you (are|will|must)\b",
    r"\bnew instructions?:",
    r"\bforget (all|your) (previous |prior )?(instructions|rules|safety)",
    r"\bdo not (follow|obey) (your|the) (safety|previous) (rules|instructions)",
]

SECRET_PATTERNS = [
    r"\bsk-[a-zA-Z0-9]{8,}\b",  # OpenAI/OpenRouter-style API keys
    r"\b(api[_ -]?key|password|passwd|secret key)\b\s*[:=]?\s*\S+",
    # credit-card-like number grouping
    r"\b\d{4}[- ]\d{4}[- ]\d{4}[- ]\d{4}\b",
]

# A third-party privacy match requires BOTH:
#   1. language identifying another person through a relationship; and
#   2. a sensitive-data keyword or an address-shaped value.
#
# The memory writer may normalize "my classmate ..." into "User's classmate ...", so both the
# original-user phrasing and the normalized memory phrasing must be recognized.
THIRD_PARTY_RELATIONSHIP_PATTERNS = [
    (
        r"\b(?:my|his|her|their|user(?:'s|’s))\s+"
        r"(?:friend|mother|father|mom|dad|sister|brother|coworker|colleague|"
        r"wife|husband|partner|boss|neighbor|neighbour|roommate|classmate)"
        r"(?:'s|’s)?\b"
    ),
]

SENSITIVE_DATA_TYPE_PATTERNS = [
    (
        r"\b(?:social security|ssn|password|credit card|medical (?:condition|history|record)|"
        r"diagnos(?:is|ed)|home address|phone number)\b"
    ),
]

# Detect a common street-address shape such as:
#   123 Fake Street
#   12 King St W
#   42 O'Connor Road
#
# This is intentionally used only together with a third-party relationship match, reducing false
# positives from harmless numbers or from the user's own non-secret address statement.
STREET_ADDRESS_PATTERNS = [
    (
        r"\b\d{1,6}\s+"
        r"(?:[a-z0-9][a-z0-9.'-]*\s+){0,6}"
        r"(?:street|st|road|rd|avenue|ave|drive|dr|lane|ln|boulevard|blvd|"
        r"court|ct|crescent|cres|place|pl|terrace|terr|trail|trl|way|highway|hwy)"
        r"(?:\s+(?:north|south|east|west|n|s|e|w))?"
        r"(?:\b|(?=[.,]))"
    ),
]


def _matches_any(patterns: list[str], text: str) -> bool:
    return any(re.search(pattern, text) for pattern in patterns)


def check(content: str) -> str | None:
    """Return a deny reason when content violates a write-time memory rule.

    The check runs on the exact text about to be written: ``save_memory.content`` or
    ``update_memory.new_content``. This means patterns must support both the user's original
    wording and normalized facts generated by the model.
    """
    lowered = content.lower()

    if _matches_any(BEHAVIOR_OVERRIDE_PATTERNS, lowered):
        return "behavior-override instruction"

    if _matches_any(SECRET_PATTERNS, lowered):
        return "secret/credential"

    has_third_party = _matches_any(THIRD_PARTY_RELATIONSHIP_PATTERNS, lowered)
    has_sensitive_data = _matches_any(
        SENSITIVE_DATA_TYPE_PATTERNS + STREET_ADDRESS_PATTERNS,
        lowered,
    )
    if has_third_party and has_sensitive_data:
        return "third-party private data"

    return None
